# -*- coding: utf-8 -*-


# x assigned to 5
# TODO: create also y
x = 5

if x == 5:
	print("yes")
elif x == 6:
	pass
else:
	print("no")

def fibonacci(number):
	"""This function calculates fibonacci number
	
	"""

for i in xrange(10):
	print(i)

class MyClass(object):
	"""This is 
	my 
	class

	"""
	def __init__(self):
		"""This is constructor"""
		self.x = 5


my_object = MyClass()


print(fibonacci.__doc__)
